# Generated by Django 4.2.11 on 2024-04-01 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('laundry_id', models.CharField(max_length=10, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('kilo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=20)),
                ('is_ready', models.BooleanField(default=False)),
                ('is_claimed', models.BooleanField(default=False)),
            ],
        ),
    ]
